docs/rock5/rock5b/accessories/camera_4k.md
docs/rock5/rock5b/accessories/display_use.md
docs/rock5/rock5b/accessories/heatsink-4012.md
docs/rock5/rock5b/accessories/m2_ekey_sata.md
docs/rock5/rock5b/accessories/metal-case.md
docs/rock5/rock5b/accessories/pd-30w.md
docs/rock5/rock5b/accessories/wifi_bt_access.md
docs/rock5/rock5b/getting-started/accessory-usage.md
docs/rock5/rock5b/getting-started/download.md
docs/rock5/rock5b/radxa-os/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/camera_4k.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/display_use.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/heatsink-4012.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/m2_ekey_sata.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/metal-case.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/pd-30w.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/wifi_bt_access.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/getting-started/accessory-usage.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/radxa-os/README.md

add buy link for accessory && add links to be more friendly to search

---

docs/compute-module/images.md
docs/compute-module/nx5/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/images.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/getting-started/download.md

feat: add nx5 io android link

---

docs/compute-module/cm5/accessories/8hd-display_use.md
docs/compute-module/cm5/accessories/camera_4k.md
docs/compute-module/cm5/accessories/camera_8m.md
docs/compute-module/cm5/accessories/rpi-7inch-display.md

update rsetup path

---

docs/compute-module/cm5/getting-started/accessory-usage.md
docs/compute-module/cm5/getting-started/install-os.md
docs/compute-module/cm5/radxa-os/os-usage/README.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/getting-started/accessory-usage.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/getting-started/install-os.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/radxa-os/apps-deploy/README.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/radxa-os/os-usage/README.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/radxa-os/apps-deploy/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/accessories/mipi-dsi.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/low-level-dev/install-os-on-emmc.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/low-level-dev/u-boot.md
i18n/en/docusaurus-plugin-content-docs/current/template/module/README.md
i18n/en/docusaurus-plugin-content-docs/current/template/sbc/README.md
i18n/en/docusaurus-plugin-content-docs/current/template/tcm/README.md
i18n/en/docusaurus-plugin-content-docs/current/x/x2l/accessories/wireless-module.md

feat: add accessory-usage 

---

docs/x/x2l/bios/update-bios.md
i18n/en/docusaurus-plugin-content-docs/current/x/x2l/bios/update-bios.md

update: x2l Bios download link

---

docs/rock3/rock3a/app-development/panfork.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/app-development/panfork.md

fix: panfork is for RK3588 SoC only

---

docs/common/dev/_kernel.mdx
docs/common/dev/_u-boot.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_kernel.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_u-boot.mdx

fix: optimize bsp documentation

---

docs/zero/zero3/app-development/panfork.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/app-development/panfork.md

fix: delete zero3 panfork

---

docs/nio/nio12l/readme.md

fix: adjust the table format to fix the pr-commit error

---

docs/common/general/_etcher.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/general/_etcher.mdx

fix: modify common etcher

---

docs/bitmain/README.md

feat:add sg2300x folder

---

docs/bitmain/README.md

fix: compile error

---

docs/nio/nio12l/install-yocto-system.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/install-yocto-system.md

fix: misspell

---

docs/compute-module/cm5/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/getting-started/download.md

feat: update cm5 rc image

---

docs/common/radxa-os/_apt-repo.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_apt-repo.mdx

please test the url is correct or not if possible(cause i dont use the offical system anymore)

add LZUOSS's mirror

---

docs/common/radxa-os/_apt-repo.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_apt-repo.mdx

Revert "add LZUOSS's mirror"

---

docs/accessories/peripherals/quectel-lte-ec25.md

fix: use the nm host lte module

---

docs/Home.md

docs: rock 5c: Add homepage index

---

docs/common/radxa-os/_apt-repo.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_apt-repo.mdx

如果可以的话烦请先测试一下目录结构是否正确以及命令是否正确(我已经不再使用官方系统所以暂时无法测试）
地址: `https://mirrors.lzu.edu.cn/radxa-apt/` (暂未在主页公开列出)

add LZU'S OSS mirror site

---

docs/accessories/penta-sata-hat/sata-hat-top-board.md
docs/common/config/_rsetup.mdx
docs/sophon/aicore-sg2300x/download.md
docs/sophon/bm168m/getting-started/download.md
docs/sophon/bm168m/getting-started/install-os.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/sata-hat-top-board.md
i18n/en/docusaurus-plugin-content-docs/current/common/config/_rsetup.mdx
i18n/en/docusaurus-plugin-content-docs/current/sophon/aicore-sg2300x/download.md
i18n/en/docusaurus-plugin-content-docs/current/sophon/bm168m/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/sophon/bm168m/getting-started/install-os.md
i18n/en/docusaurus-plugin-content-docs/current/sophon/bm168m/getting-started/preparation.md

fix: add system upgrade warning

---

docs/Home.md

refactor: Annotate document information

---

docs/common/dev/_nvme.mdx
docs/compute-module/cm5/hardware/hw-interface.md
docs/rock3/rock3c/low-level-dev/install-os-on-nvme.md
docs/rock5/rock5b/low-level-dev/install-os-on-nvme.md
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_nvme.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/general/_serial.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/low-level-dev/install-os-on-nvme.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/install-os-on-nvme.md

fix: add rsetup link

---

docs/Home.md

docs: deleting document templates

---

docs/bitmain/README.md
docs/sophon/aicore-sg2300x/README.md
docs/sophon/airbox/README.md
i18n/en/docusaurus-plugin-content-docs/current/sophon/aicore-sg2300x/README.md
i18n/en/docusaurus-plugin-content-docs/current/sophon/airbox/README.md

refactor:remove radxa from sg series's aicore and airbox title

---

docs/compute-module/cm5/hardware/revisions.md
docs/rock5/rock5a/hardware/revisions.md

feat:add rock5a hardware revision history

---

i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/hardware/revisions.md

feat:add cm5 hardware revision history(en)

---

docs/compute-module/cm5/faq.md
docs/compute-module/cm5/hardware/README.md
docs/compute-module/cm5/hardware/hw-interface.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/faq.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/hardware/README.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/hardware/hw-interface.md

feat:add faq for cm5

---

i18n/en/docusaurus-theme-classic/navbar.json
i18n/zh/docusaurus-theme-classic/navbar.json

feat: modify navbar

---

docs/rock5/rock5c/download.md
docs/rock5/rock5c/getting-started/install-os.md
docs/rock5/rock5c/low-level-dev/install-os-via-usb-otg.md
docs/rock5/rock5c/other-os/README.md
docs/rock5/rock5c/other-os/android/README.md
docs/rock5/rock5c/other-os/android/install-os.md
docs/rock5/rock5c/other-os/android/low-level-dev.md
docs/rock5/rock5c/other-os/android/preparation.md
docs/rock5/rock5c/other-os/android/remote-login.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/getting-started/install-os.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/low-level-dev/install-os-via-usb-otg.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/other-os/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/other-os/android/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/other-os/android/install-os.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/other-os/android/low-level-dev.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/other-os/android/preparation.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/other-os/android/remote-login.md

refactor:rock5c download directory structure

docs: rock5c add adnroid document

---

docs/rockpi/rockpis/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/download.md

Add rockpis image download links to the Chinese and English documentation.

docs: add rockpis mirror download resource

---

docs/zero/zero3/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/download.md

fix: fix zero3 download items style

---

docs/common/ai/_casaos_app_install.mdx
docs/common/ai/_sd_lcm.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_casaos_app_install.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_sd_lcm.mdx

fix: remove .md to avoid warning in sd-lcm.mdx

fix: remove .md to avoid warning

---

docs/accessories/penta-sata-hat/sata-hat-top-board.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/sata-hat-top-board.md

fix: fix penta hat name

---

i18n/en/docusaurus-plugin-content-docs/current/accessories/wireless-a8.md

a8: modifid chinese to english

---

docs/rock5/rock5itx/getting-started/preparation.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/getting-started/preparation.md

perf:  add monitor tips for rock 5 itx

---

docs/accessories/penta-sata-hat/sata-hat-top-board.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/sata-hat-top-board.md

docs: modify penta top board name

---

docs/rock5/rock5itx/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/getting-started/download.md

fix: fix the caution

---

docs/rock5/rock5itx/getting-started/hardware-overview.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/getting-started/hardware-overview.md

Radxa rock 5 itx fan

---

i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/getting-started/assembly-guide.md

fix: delete extra space

---

docs/rock5/rock5itx/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/README.md

fix: fix the broken guide link

---

docs/rock5/rock5c/radxa-os/README.md
docs/rock5/rock5c/radxa-os/audio.md
docs/rock5/rock5c/radxa-os/locale.md
docs/rock5/rock5c/radxa-os/media.md
docs/rock5/rock5c/radxa-os/network.md
docs/rock5/rock5c/radxa-os/office.md
docs/rock5/rock5c/radxa-os/remote-access.md
docs/rock5/rock5c/radxa-os/serial.md
docs/rock5/rock5c/radxa-os/social.md
docs/rock5/rock5c/radxa-os/software.md
docs/rock5/rock5c/radxa-os/using-apt.md
docs/rock5/rock5c/radxa-os/video.md
docs/rock5/rock5itx/radxa-os/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/audio.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/locale.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/media.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/network.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/office.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/remote-access.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/serial.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/social.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/software.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/usbnet.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/using-apt.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/video.md

refactor: optimize radxa-os for 5c

---

docs/rock5/rock5c/apps-deployment/klipper.md
docs/rock5/rock5c/apps-deployment/samba.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/apps-deployment/klipper.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/apps-deployment/samba.md

Apps deployment 5c

---

docs/rock5/rock5c/getting-started/install-os.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/getting-started/install-os.md

fix: element Line Breaks

---

docs/common/dev/_rknn-toolkit-lite2-yolov8.mdx
docs/rock5/rock5b/app-development/rknn_toolkit_lite2_yolov8.md
docs/rock5/rock5c/app-development/rknn_toolkit_lite2_yolov8.md
docs/rock5/rock5itx/app-development/rknn_toolkit_lite2_yolov8.md
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_sd_lcm.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rknn-toolkit-lite2-yolov8.mdx

- add rknn yolov8 pre-converted notification in docs
- fix rknn yolov8 chinese index problem
closes #50

add rknn yolov8 pre-converted notification in docs 

---

docs/accessories/dc12-60w.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/dc12-60w.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/heatsink-7518b.md

modified format on rock 5 itx

---

docs/accessories/pd_30w.md

fix: rename title

---

docs/zero/zero/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero/getting-started/download.md

* close https://github.com/radxa-docs/docs/issues/119

fix: zero: repair not correctly line feeds

---

docs/rock5/rock5b/low-level-dev/rkdeveloptool.md
docs/rock5/rock5b/low-level-dev/rkdevtool.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/rkdeveloptool.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/rkdevtool.md

fix: fix the loader missing issue of 5b

---

docs/x/roobi/README.md
i18n/en/docusaurus-plugin-content-docs/current/x/roobi/README.md

fix: fix roobi readme

---

docs/common/config/_rsetup.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/config/_rsetup.mdx

fix: details label display problem

---

docs/common/apps/_msodbcsql.mdx
docs/rock3/e25/apps-deployment/msodbcsql.md
docs/rock3/rock3a/apps-deployment/msodbcsql.md
docs/rock3/rock3c/apps-deployment/msodbcsql.md
docs/rock5/rock5b/apps-deployment/msodbcsql.md
docs/rock5/rock5c/apps-deployment/msodbcsql.md
docs/rock5/rock5itx/apps-deployment/msodbcsql.md
docs/rockpi/rocks0/apps-deployment/msodbcsql.md
docs/template/sbc/apps-deployment/msodbcsql.md
docs/template/tcm/apps-deployment/msodbcsql.md
docs/zero/zero/apps-deployment/msodbcsql.md
docs/zero/zero2pro/apps-deployment/msodbcsql.md
docs/zero/zero3/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/heatsink-8418b.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/faq.md

add Install the Microsoft ODBC driver for SQL Server Docs and resolve some pre-commit checked issues

---

docs/rock5/rock5itx/getting-started/install-os/eMMC.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/getting-started/install-os/eMMC.md

fix: fix the tab missing queryString

---

i18n/en/docusaurus-plugin-content-docs/current/common/apps/_msodbcsql.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock3/e25/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rocks0/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/template/sbc/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/template/tcm/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/apps-deployment/msodbcsql.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/apps-deployment/msodbcsql.md

feat: add Install the Microsoft ODBC driver for SQL Server English Docs

---

docs/accessories/penta-sata-hat/penta-for-rpi5.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/penta-for-rpi5.md

docs: add penta power info

---

docs/accessories/penta-sata-hat/the-penta-sata-hat.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/the-penta-sata-hat.md

docs: add penta peak current

---

i18n/en/docusaurus-plugin-content-docs/current/common/config/_rsetup.mdx

fix: rsetup: correction of incorrect syntax

---

docs/common/dev/_rkdevtool.mdx
docs/common/general/_loader.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rkdevtool.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/general/_loader.mdx

fix: loader file doesn't show in rkdevtool

---

docs/rock3/rock3a/other-os/android/low-level-dev.md

fix: fix the broken  source code of android 12

---

docs/roobi/README.md
i18n/en/docusaurus-plugin-content-docs/current/roobi/README.md

Signed-off-by: Nascs Fang <nascs@radxa.com>

feat: add roobi

---

docs/accessories/penta-sata-hat/raid-with-mdadm.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/raid-with-mdadm.md

docs: penta add mdadm raid

---

docs/common/ai/_chatbot_llama3.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_chatbot_llama3.mdx

llama3 docs add languages setting and role-playing feature

docs: llama3 docs add languages setting and role-playing feature

---

docs/rock5/rock5itx/getting-started/interface-usage/pcie-m-key.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/getting-started/interface-usage/pcie-m-key.md

fix: fix the fio img missing issue

---

docs/common/general/_etcher.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/general/_etcher.mdx

fix: let the sd_slot do not display default

---

docs/rock5/rock5b/accessories/m2_ekey_sata.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/accessories/m2_ekey_sata.md

fix: fix the software-configuration of sata

---

docs/rock5/rock5a/app-development/README.md
docs/rock5/rock5a/app-development/gpiod.md
docs/rock5/rock5a/app-development/hdmi-rx.md
docs/rock5/rock5a/app-development/mraa.md
docs/rock5/rock5a/app-development/opencv.md
docs/rock5/rock5a/app-development/panfork.md
docs/rock5/rock5a/app-development/pin-40-test.md
docs/rock5/rock5a/app-development/qt_cross_compile.md
docs/rock5/rock5a/app-development/rknn_install.md
docs/rock5/rock5a/app-development/rknn_toolkit2_pc.md
docs/rock5/rock5a/app-development/rknn_toolkit_lite2_yolov8.md
docs/rock5/rock5a/app-development/rtsp.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/gpiod.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/hdmi-rx.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/mraa.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/opencv.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/panfork.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/pin-40-test.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/qt_cross_compile.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/rknn_install.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/rknn_toolkit2_pc.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/rknn_toolkit_lite2_yolov8.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/rtsp.md

App dev 5a

---

docs/common/general/_loader.mdx
docs/rock5/lowlevel-development/bootloader_spi_flash.md
docs/rock5/rock5a/getting-started/rkdevtool.md
docs/rock5/rock5b/low-level-dev/bootloader_spi_flash.md
docs/rock5/rock5b/low-level-dev/erase-spi-from-usb-otg.md
docs/rock5/rock5itx/low-level-dev/maskrom/linux.md
docs/rock5/rock5itx/low-level-dev/maskrom/windows.md
docs/rock5/rock5itx/other-os/android/install-os.md
i18n/en/docusaurus-plugin-content-docs/current/common/general/_loader.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/lowlevel-development/bootloader_spi_flash.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/getting-started/rkdevtool.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/bootloader_spi_flash.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/erase-spi-from-usb-otg.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/low-level-dev/maskrom/linux.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/low-level-dev/maskrom/mac-os.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/low-level-dev/maskrom/windows.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/other-os/android/install-os.md

refactor:update rock5 loader & spi uboot patch

---

docs/common/ai/_casaos_app_install.mdx
docs/common/ai/_tpu_inference.mdx
docs/sophon/airbox/model-compile/tpu_inference.md
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_casaos_app_install.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_tpu_inference.mdx
i18n/en/docusaurus-plugin-content-docs/current/sophon/airbox/model-compile/tpu_inference.md

change sd casaos docker image tag 0.1.0 -> 0.3.0

docs: change sd casaos docker image tag 0.1.0 -> 0.3.0

---

docs/sophon/airbox/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/sophon/airbox/getting-started/download.md

fix:no image link in en docs

---

docs/rock5/rock5b/other-os/android/low-level-dev.md

fix: Android source code download address error

---

docs/zero/zero/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero/getting-started/download.md

* closes https://github.com/radxa-docs/docs/issues/194

fix: zero: add v1.51 hardware design files

---

docs/common/ai/_casaos_intro.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_casaos_intro.mdx

docs: add casaos install zh/en usage

docs: add casaos install zh/en usage

---

docs/rock3/rock3c/hardware-design/hardware-interface.md
docs/zero/zero3/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/hardware-design/hardware-interface.md

feat: add csi & dsi pin definition

---

docs/rock5/rock5b/low-level-dev/bootloader_spi_flash.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/bootloader_spi_flash.md

fix: delete rkspi_loader

---

docs/rock5/rock5c/_image.mdx
docs/rock5/rock5c/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/download.md

feat: add rock 5c android 12 imgs

---

docs/compute-module/cm5/getting-started/download.md
docs/compute-module/images.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/images.md

update cm5 download image

---

docs/rock5/rock5c/getting-started/power-supply.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/getting-started/power-supply.md

fix: fix the power supply

---

i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/README.md

fix: penta en page add doccardlist

---

docs/common/accessories/_camera-usage.mdx
docs/common/accessories/_fan.mdx
docs/common/dev/_u-boot.mdx
docs/compute-module/cm3/lowlevel-development/kernel.md
docs/compute-module/cm3/lowlevel-development/rbuild.md
docs/compute-module/cm3/lowlevel-development/rkdeveloptool.md
docs/compute-module/cm3/lowlevel-development/rkdevtool.md
docs/compute-module/cm3/lowlevel-development/spi-nor-flash.md
docs/compute-module/cm3/lowlevel-development/u-boot.md
i18n/en/docusaurus-plugin-content-docs/current/common/accessories/_camera-usage.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/accessories/_fan.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_u-boot.mdx
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/lowlevel-development/kernel.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/lowlevel-development/rbuild.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/lowlevel-development/rkdeveloptool.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/lowlevel-development/rkdevtool.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/lowlevel-development/spi-nor-flash.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/lowlevel-development/u-boot.md

Low dev cm3

---

i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/low-level-dev/install-os-on-emmc.md

fix: zero2: replace zero-related descriptions with zero2pro

---

i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rkdeveloptoolV2.mdx

fix: fix the translation issue of rkdeveloptool

---

docs/compute-module/README.md
docs/e/README.md
docs/e/e20c/.radxa-os/README.md
docs/e/e20c/faq.md
docs/e/e20c/hardware-design/README.md
docs/e/e20c/istoreos/README.md
docs/e/e20c/other-os/README.md
docs/rock3/README.md
docs/rockpi/README.md
docs/roobi/README.md
docs/sophon/README.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/README.md
i18n/en/docusaurus-plugin-content-docs/current/e/README.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/.radxa-os/README.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/faq.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/hardware-design/README.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/istoreos/README.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/other-os/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/products.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/README.md
i18n/en/docusaurus-plugin-content-docs/current/roobi/README.md
i18n/en/docusaurus-plugin-content-docs/current/sophon/README.md

Fix route build issues

---

docs/compute-module/README.md
docs/rockpi/README.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/README.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/README.md

fix: fix the build error

---

docs/rock5/rock5itx/getting-started/introduction.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/getting-started/introduction.md

fix: fix the table of 5itx interface

---

docs/rock3/rock3b/_image.mdx
docs/rock3/rock3b/low-level-dev/maskrom/erase.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/low-level-dev/maskrom/erase.md

fix: fix the 3b loader issue

---

docs/rock3/rock3b/getting-started/quick-start.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/getting-started/quick-start.md

fix: fix the hdmi cable

---

docs/e/e20c/download.md
docs/e/e20c/getting-started/install-os/maskrom/linux_macos.md
docs/e/e20c/getting-started/install-os/maskrom/windows.md
docs/e/e20c/other-os/debian.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/download.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/getting-started/install-os/README.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/getting-started/install-os/maskrom/linux_macos.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/getting-started/install-os/maskrom/windows.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/other-os/README.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/other-os/debian.md

feat:add debian cli for e20c

---

docs/e/e20c/download.md

fix: replace the e20c system image with xfce version

---

docs/sophon/airbox/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/sophon/airbox/hardware-design/hardware-interface.md

fix: fix airbox wifibt supported list

---

i18n/en/docusaurus-plugin-content-docs/current/e/e20c/download.md

fix: replace the e20c system image with xfce version in en page

---

docs/common/dev/_opencv.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_opencv.mdx

feat: add opencv manual compilation method

---

docs/nio/nio12l/download/README.md
docs/nio/nio12l/installation/install-ubuntu-image-on-linux-pc.md
docs/nio/nio12l/installation/install-ubuntu-image-on-windows-pc.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/download/README.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/installation/install-ubuntu-image-on-linux-pc.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/installation/install-ubuntu-image-on-windows-pc.md

Update NIO 12L Ubuntu image and flash guide

---

docs/compute-module/cm5/getting-started/download.md
docs/compute-module/images.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/images.md

fix: fix the cm5 io image name

---

.cz.toml
docs/common/radxa-os/_mali-gpu.mdx
docs/compute-module/cm5/getting-started/download.md
docs/compute-module/cm5/radxa-os/mali-gpu.md
docs/compute-module/nx5/radxa-os/mali-gpu.md
docs/rock5/rock5a/radxa-os/mali-gpu.md
docs/rock5/rock5b/radxa-os/mali-gpu.md
docs/rock5/rock5c/radxa-os/mali-gpu.md
docs/rock5/rock5itx/radxa-os/mali-gpu.md
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_mali-gpu.mdx
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/radxa-os/mali-gpu.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/radxa-os/mali-gpu.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/radxa-os/mali-gpu.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/radxa-os/mali-gpu.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/radxa-os/mali-gpu.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/radxa-os/mali-gpu.md

feat: rk3588: add enable Panthor docs

---

docs/common/yocto/_yocto-rockchip.mdx
docs/rock5/rock5b/other-os/yocto.md
docs/rock5/rock5c/other-os/yocto.md
i18n/en/docusaurus-plugin-content-docs/current/common/yocto/_yocto-rockchip.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/other-os/yocto.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/other-os/yocto.md

Add Yocto rockchip build

---

docs/rock5/rock5b/_image.mdx
docs/rock5/rock5b/download.md
docs/rock5/rock5b/getting-started/install-os/boot_from_emmc.md
docs/rock5/rock5b/getting-started/install-os/boot_from_sd_card.md
docs/rock5/rock5b/low-level-dev/maskrom/linux.md
docs/rock5/rock5b/low-level-dev/maskrom/mac-os.md
docs/rock5/rock5b/low-level-dev/maskrom/windows.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/getting-started/install-os/boot_from_emmc.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/getting-started/install-os/boot_from_sd_card.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/maskrom/linux.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/maskrom/mac-os.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/maskrom/windows.md

feat: add rock5b 6.1 image

---

docs/common/dev/_erase-spi-emmc.mdx
docs/rock3/rock3b/low-level-dev/maskrom/erase.md
docs/rock5/rock5a/low-level-dev/maskrom/erase.md
docs/rock5/rock5b/low-level-dev/maskrom/erase.md
docs/rock5/rock5c/low-level-dev/maskrom/erase.md
docs/rock5/rock5itx/low-level-dev/maskrom/erase.md
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_erase-spi-emmc.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/low-level-dev/maskrom/erase.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/low-level-dev/maskrom/erase.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/maskrom/erase.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/low-level-dev/maskrom/erase.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/low-level-dev/maskrom/erase.md

Fix erase spi emmc common

---

docs/compute-module/cm3i/app-development/hdmi-rx.md
docs/rock5/rock5a/app-development/hdmi-rx.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/app-development/hdmi-rx.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/hdmi-rx.md

Hdmiin delete

---

docs/x/x2l/software-development/gpio.md
i18n/en/docusaurus-plugin-content-docs/current/x/x2l/software-development/gpio.md

fix: fix x2l gpio displaying issue

---

docs/accessories/penta-sata-hat/sata-hat-top-board.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/sata-hat-top-board.md

 update software for rockpi-penta

---

docs/common/dev/_i2c.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_i2c.mdx

fix: fix the oled display issue

---

i18n/en/docusaurus-plugin-content-docs/current/x/x4/accessories/README.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/bios/README.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/hardware/README.md

docs: modified info on radxa x4

---

docs/x/x4/software/flash.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/software/flash.md

fix: fix the rp2040 reboot script

---

docs/roobi/install-roobi.md
i18n/en/docusaurus-plugin-content-docs/current/roobi/install-roobi.md

docs: remove show expanding for roobi download links

---

docs/x/x4/bios/update-bios.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/bios/update-bios.md

fix: use a link to store versions of bios

---

docs/x/x4/bios/update-bios.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/bios/update-bios.md

fix: fix the https for x4 bios download address

---

docs/x/x4/software/flash.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/software/flash.md

fix: fix the x4 hardware bootsel description

---

docs/common/dev/_pico-poe-fan.mdx
docs/x/x4/accessories/25w-poe-plus-hat-for-x.md
docs/x/x4/software/c_sdk_examples.md
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_pico-poe-fan.mdx
i18n/en/docusaurus-plugin-content-docs/current/x/x4/accessories/25w-poe-plus-hat-for-x.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/software/c_sdk_examples.md

feat: add poe fan for x4

---

docs/e/e20c/download.md
docs/rock2/rock2a/download.md
docs/rock2/rock2a/getting-started/install-os/maskrom/linux.md
docs/rock2/rock2a/getting-started/install-os/maskrom/macos.md
docs/rock2/rock2a/getting-started/install-os/maskrom/windows.md
docs/rock2/rock2f/download.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/getting-started/install-os/maskrom/linux.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/getting-started/install-os/maskrom/macos.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/getting-started/install-os/maskrom/windows.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2f/download.md

fix: modify the naming of the mirror file download and add a description of e and rock2 series
Signed-off-by: SongJun Li <lisongjun@radxa.com>

fix: modify the naming of the mirror file download and add a description of e and rock2 series

---

docs/common/radxa-os/_ap-and-sta.mdx
docs/rock2/rock2a/radxa-os/ap-station.md
docs/rock2/rock2f/radxa-os/ap-station.md
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_ap-and-sta.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/radxa-os/ap-station.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2f/radxa-os/ap-station.md

feat: add create Wi-Fi AP and set station mode docs
Signed-off-by: SongJun Li <lisongjun@radxa.com>

feat: add create Wi-Fi AP and set station mode docs

---

docs/e/e20c/download.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/download.md

docs: added openwrt links on e20c

---

i18n/en/docusaurus-plugin-content-docs/current/e/e20c/download.md

* closes https://github.com/radxa-docs/docs/issues/375

fix: e20c: remove the link from the image name

---

docs/e/e20c/download.md
i18n/en/docusaurus-plugin-content-docs/current/e/e20c/download.md

fix: Fix spelling on e20c

---

docs/compute-module/cm3/getting-started/interface-usage/pin-40-test.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/getting-started/interface-usage/pin-40-test.md

fix: delete waveshare35b for cm3-io

---

docs/common/ai/_casaos_app_build.mdx
docs/common/ai/_sd_lcm.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_casaos_app_build.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_sd_lcm.mdx

docs: change the link of tpu-mlir whl for sd1.5

docs: change the link of tpu-mlir whl for sd1.5

---

docs/nio/nio12l/low-level-dev/build-yocto.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/low-level-dev/build-yocto.md

feat: nio-12l: use new yocto build guide

---

docs/rock3/images.md
docs/rock3/rock3c/getting-started/download.md
docs/rock5/rock5b/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock3/images.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/_image.mdx

Release os

---

docs/rock5/rock5c/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/_image.mdx

feat: rock-5c: use debian12 b1 os

---

docs/rock3/rock3c/app-development/READNE.md
docs/rock3/rock3c/app-development/mraa.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/app-development/READNE.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/app-development/mraa.md

feat: add mraa to 3c

---

docs/nio/nio12l/low-level-dev/build-ubuntu-kernel.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/low-level-dev/build-ubuntu-kernel.md

feat: nio-12l: use radxa kernel tree to build ubuntu kernel

---

docs/rock5/rock5c/other-os/armbian.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/other-os/armbian.md

feat: rock-5c: add armbian guide

---

docs/zero/zero3/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/download.md

feat: add zero 3w openipc image

---

docs/common/radxa-os/_remote-access.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_remote-access.mdx

* closes https://github.com/radxa-docs/docs/issues/402

fix: common: optimize SSH related documents

---

.github/CODEOWNERS
docs/compute-module/cm3/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/download.md

* closes https://github.com/radxa-docs/docs/issues/274

feat: cm3: add datasheet

---

docs/sirider/s1/app-development/zhouyi_npu.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/app-development/zhouyi_npu.md

docs: add env prepare for aipu installtion

docs: add env prepare for aipu installtion

---

docs/sirider/s1/low-level-dev/README.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/low-level-dev/README.md

feat: add low level dev folder

---

i18n/en/code.json
i18n/zh/code.json
static/home/meun.svg

添加导航栏的中英文翻译

---

docs/sirider/s1/getting-started/install-os/boot_from_emmc.md
docs/sirider/s1/getting-started/introduction.md
docs/sirider/s1/low-level-dev/image_build.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/getting-started/install-os/boot_from_emmc.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/getting-started/introduction.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/low-level-dev/image_build.md

Add sirider s1 image build doc

---

docs/compute-module/cm5/getting-started/download.md
docs/compute-module/images.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/images.md

docs: feat: update cm5 kernal 6.1 image link

---

docs/sirider/s1/getting-started/install-os/boot_from_emmc.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/getting-started/install-os/boot_from_emmc.md

docs: sirider s1: add flash tool doc

---

i18n/en/docusaurus-plugin-content-docs/current/productlist.md
i18n/en/docusaurus-theme-classic/navbar.json

feat: add SiRider Series

---

docs/compute-module/cm5/android/install-os.mdx
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/android/install-os.mdx

fix: fix the rkdev tools link error

---

i18n/en/docusaurus-plugin-content-docs/current/accessories/pd_65w.md

fix: fixed file name and modified info

---

docs/rock5/rock5a/low-level-dev/kernel.md
docs/rock5/rock5c/low-level-dev/kernel.md
docs/rock5/rock5itx/low-level-dev/kernel.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/low-level-dev/kernel.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/low-level-dev/kernel.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/low-level-dev/kernel.md

Fix rock5 kernel build

---

docs/common/dev/_rtsp.mdx

fix: rename rtsp to hw-codec and update the content

---

docs/common/config/_rsetup.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/config/_rsetup.mdx

perf: rsetup: add Configure auto login feature description

---

docs/nio/nio12l/yocto/README.md
docs/nio/nio12l/yocto/yocto-user-guide.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/yocto/README.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/yocto/yocto-user-guide.md

feat: nio-12l: add yocto user guide

---

docs/nio/nio12l/android/how-to-build-andoid.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/android/how-to-build-andoid.md

feat: add android's build method

---

docs/rock5/rock5itx/_image.mdx
docs/rock5/rock5itx/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/download.md

fix: fix code style bugs

---

docs/common/dev/_rtsp.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rtsp.mdx

fix: common: rtsp: update translations and fixed text errors

---

.github/CODEOWNERS
.github/workflows/deploy.yaml

Fix pre-commit installation failure

ci: use pipx instead of pip

---

docs/common/dev/_rtsp.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rtsp.mdx

fix: rtsp: add Debian 11 build tip

---

docs/sirider/s1/download.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/download.md

feat: add sirider s1 hw docs

---

docs/common/ai/_flux_1.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_flux_1.mdx

docs: flux.1 zh/en add gradio usage

---

docs/common/dev/_ros2-humble-compilation.mdx
docs/rock5/rock5a/app-development/ros2_humble.md
docs/rock5/rock5b/app-development/ros2_humble.md
docs/rock5/rock5c/app-development/ros2_humble.md
docs/rock5/rock5itx/app-development/ros2_humble.md
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_ros2-humble-compilation.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/ros2_humble.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/app-development/ros2_humble.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/app-development/ros2_humble.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/app-development/ros2_humble.md

Ros2 humble

---

docs/rock3/e25/download.md
docs/rock3/rock3a/getting-started/download.md
docs/rock4/rock4ab/download.md
docs/rockpi/rockpie/download.md
docs/rockpi/rockpis/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/e25/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock4/rock4ab/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpie/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/download.md

Openwrt images

---

docs/common/dev/_kernel.mdx
docs/common/dev/_u-boot.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_kernel.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_u-boot.mdx

fix: add details to the bsp parameter --no-prepare-source

---

docs/common/config/rsetup/_add-led.mdx
docs/common/config/rsetup/_disable-fiq.mdx
docs/common/config/rsetup/_enable-uart2-m0.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/config/rsetup/_add-led.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/config/rsetup/_disable-fiq.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/config/rsetup/_enable-uart2-m0.mdx

fix: fix the rsetup title

---

docs/common/dev/_android-name.mdx
docs/rock5/rock5b/other-os/android/install-os.md

docs: Add SSD burning steps

---

docs/common/dev/_pico-uart.mdx
docs/x/x2l/software-development/c_sdk_examples.md
docs/x/x4/software/c_sdk_examples.md
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_pico-uart.mdx
i18n/en/docusaurus-plugin-content-docs/current/x/x2l/software-development/c_sdk_examples.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/software/c_sdk_examples.md

Uart com x2l

---

docs/rock5/rock5b/getting-started/interface-usage/pcie-m-key.md

Add M-key 970 evo plus nmve read write speed

Update pcie-m-key.md add 970 evo-plus r/w speed

---

docs/sophon/airbox/getting-started/preparation.md
i18n/en/docusaurus-plugin-content-docs/current/sophon/airbox/getting-started/preparation.md

docs: change airbox power value

docs: change airbox power value

---

docs/rock5/rock5b/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/hardware-design/hardware-interface.md

feat: add mipi csi/dsi line sequences

---

docs/common/dev/_mraa.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_mraa.mdx

fix: add notes to the mraa pwm function

---

.github/CODEOWNERS
docs/common/radxa-os/_mali-gpu.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_mali-gpu.mdx

Optimize gpu switching documentation

---

docs/common/radxa-os/_mali-gpu.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_mali-gpu.mdx

fix: fix some syntax errors

---

docs/common/radxa-os/_apt-repo.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_apt-repo.mdx

fix: correction of repo.list information

---

docs/common/radxa-os/_display.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_display.mdx

feat: display: add persistence configuration

---

docs/common/dev/_mraa.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_mraa.mdx

fix: fix the mraa source code installation

---

docs/x/x4/software/micro_python.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/software/micro_python.md

fix: fix the thonny version issue

---

docs/compute-module/cm5/radxa-os/app-dev/ros2_humble.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/radxa-os/app-dev/ros2_humble.md

feat: port ros2 to cm5

---

docs/common/general/_loader.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/general/_loader.mdx

fix: add zero 3 loader item

---

docs/rock5/faq.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/faq.md

fix: rock-5a spi fla sales strategy has changed

---

docs/common/dev/_kernel.mdx
docs/common/dev/_u-boot.mdx

Move the text out of the code block and repair the indentation of the code block

style: adjust the code block

---

docs/rockpi/rocks0/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rocks0/getting-started/download.md

feat: add pi s0 v1.2 version hw en docs

---

docs/e/e52c/download.md
i18n/en/docusaurus-plugin-content-docs/current/e/e52c/download.md

feat: e52c: update the debian image version

---

i18n/en/docusaurus-plugin-content-docs/current/common/general/_power_board_from_40pin.mdx

fix: wrong order of pics in the power of board from 40 pin en docs

---

docs/common/general/_sddisktool.mdx
docs/zero/zero3/other-os/buildroot.md
i18n/en/docusaurus-plugin-content-docs/current/common/general/_sddisktool.mdx
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/other-os/buildroot.md

feat: zero3: add burning sdcard with sddisktool

---

docs/compute-module/cm3i/download.md
docs/compute-module/cm3i/low-level-dev/README.md
docs/compute-module/cm3i/other-os/README.md
docs/compute-module/cm3i/other-os/android/install-os.mdx
docs/compute-module/cm3i/other-os/android/low-level-dev.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/low-level-dev/README.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/other-os/README.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/other-os/android/install-os.mdx
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/other-os/android/low-level-dev.md

docs: Added cm3i installation Android documentation

---

docs/rock3/rock3c/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/hardware-design/hardware-interface.md

fix: delete non-existent adc

---

docs/rock5/rock5c/other-os/buildroot.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/other-os/buildroot.md

feat: add rock 5c buildroot

---

docs/sirider/s1/download.md

add sirider s1 img

---

docs/sirider/s1/getting-started/introduction.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/getting-started/introduction.md

fix: remove emmc config in sirider s1 spec

---

docs/compute-module/nx5/getting-started/download.md
docs/rock5/rock5a/_image.mdx
docs/rock5/rock5itx/_image.mdx
docs/rock5/rock5itx/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3i/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/download/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/download.md

add 6.1 image for radxa nx5 io rock 5a and rock 5 itx

---

.github/CODEOWNERS
.gitownrc
docs/accessories/wireless-a8.md
docs/common/radxa-os/_ap.mdx
i18n/en/docusaurus-plugin-content-docs/current/accessories/wireless-a8.md
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_ap.mdx
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/download.md

fix: add Q&A for Wireless card

---

docs/sirider/s1/getting-started/interface-usage/pin-40-test.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/getting-started/interface-usage/pin-40-test.md

fix: add 40pin description for sirider s1

---

i18n/en/docusaurus-plugin-content-docs/current/accessories/dc12-60w.md

docs: add dc-12v 60w polarity (en)

---

docs/rock5/rock5a/_image.mdx
docs/rock5/rock5a/download.md
docs/rock5/rock5a/other-os/android/README.md
docs/rock5/rock5a/other-os/android/getting-started.md
docs/rock5/rock5a/other-os/android/install-os.md
docs/rock5/rock5a/other-os/android/low-level-dev.md
docs/rock5/rock5a/other-os/android/remote-login.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/other-os/android/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/other-os/android/getting-started.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/other-os/android/install-os.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/other-os/android/low-level-dev.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/other-os/android/remote-login.md

Rock5a android docs

---

i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/download.md

docs: ROCK 2A updates images en

---

docs/rock2/rock2a/download.md

docs: ROCK 2A updates images zh

---

docs/common/dev/_redroid.mdx
docs/rock5/rock5b/app-development/redroid.md
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_redroid.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/app-development/redroid.md

docs: Add redroid docs for rock5b/5b+

---

docs/rock5/rock5b/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/download.md

docs: added 5b+ hardware files

---

docs/rock3/rock3a/getting-started/download.md
docs/rock5/rock5a/_image.mdx
docs/rock5/rock5a/download.md
docs/rockpi/rockpis/download.md
docs/zero/zero/getting-started/download.md
docs/zero/zero3/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/download.md

Dietpi images

---

docs/rockpi/rockpis/low-level-dev/README.md
docs/rockpi/rockpis/low-level-dev/kernel.md
docs/rockpi/rockpis/low-level-dev/overlays.md
docs/rockpi/rockpis/low-level-dev/rbuild.md
docs/rockpi/rockpis/low-level-dev/u-boot.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/low-level-dev/README.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/low-level-dev/kernel.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/low-level-dev/overlays.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/low-level-dev/rbuild.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/low-level-dev/u-boot.md

Signed-off-by: Nascs Fang <nascs@radxa.com

feat: add low-level-dev for rockpis

---

docs/rock5/rock5b/getting-started/introduction.md
docs/sirider/s1/hardware-design/README.md
docs/sirider/s1/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_gpio.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/getting-started/introduction.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/hardware-design/README.md
i18n/en/docusaurus-plugin-content-docs/current/sirider/s1/hardware-design/hardware-interface.md

fix:fix wrong ethernet specs of rock5b

---

docs/common/dev/_rkdevtool.mdx
docs/common/general/_loader.mdx
docs/rockpi/rocks0/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_gpio.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rkdevtool.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/general/_loader.mdx
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rocks0/getting-started/download.md

docs: added 3308 loader and RKDevTool v2.86

---

i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/other-os/android/low-level-dev.md

fix: ROCK 5 ITX android code download link

---

docs/common/dev/_ros2-humble-compilation.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_ros2-humble-compilation.mdx

fix: fix the vcstool installation issue

---

.github/CODEOWNERS
docs/common/dev/_moonlight.mdx
docs/rock5/rock5a/app-development/moonlight.md
docs/rock5/rock5b/app-development/moonlight.md
docs/rock5/rock5c/app-development/moonlight.md
docs/rock5/rock5itx/app-development/moonlight.md
docs/template/sbc/app-development/moonlight.md
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_moonlight.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/moonlight.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/app-development/moonlight.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/app-development/moonlight.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/app-development/moonlight.md
i18n/en/docusaurus-plugin-content-docs/current/template/sbc/app-development/moonlight.md

feat: common: dev: add moonlight

---

docs/roobi/README.md
i18n/en/docusaurus-plugin-content-docs/current/roobi/README.md

fix: roobi: Link address error

---

docs/common/dev/_kernel.mdx
docs/common/dev/_u-boot.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_kernel.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_u-boot.mdx

fix: complete other product parameters table

---

docs/orion/o6/download.md
docs/orion/o6/getting-started/introduction.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/download.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/getting-started/introduction.md

O6: add image download link

---

i18n/en/docusaurus-plugin-content-docs/current/orion/o6/getting-started/quick-start.md

fix: fix incorrect string

---

docs/common/config/_rsetup.mdx
docs/common/radxa-os/_usbnet.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/config/_rsetup.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_usbnet.mdx

refactor: radxa-os: change to use rsetup enable usbnet

---

docs/compute-module/cm3j/app-development/panfork.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3j/app-development/panfork.md

fix: fix build error

---

docs/compute-module/cm3j/app-development/panfork.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3j/app-development/panfork.md

fix: delete the mising panfork

---

docs/rock5/rock5b/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/hardware-design/hardware-interface.md

fix: complete PCIe info of ROCK 5B/5B+

---

docs/rock5/rock5t/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5t/hardware-design/hardware-interface.md

Fix rock 5t hardware info

---

docs/rock5/rock5b/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/hardware-design/hardware-interface.md

fix: add rock 5b+ hardware info

---

docs/compute-module/cm5/getting-started/download.md
docs/rock5/rock5a/download.md
docs/rock5/rock5b/download.md
docs/rock5/rock5t/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5t/download.md

feat: add some 2d 3d file

---

docs/zero/zero/getting-started/download.md
docs/zero/zero3/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/download.md

Move dietpi to third img

---

i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/app-development/README.md

fix: fix docs card for rock 5itx app dev

---

i18n/en/docusaurus-theme-classic/navbar.json

fix: english translation of the navigation bar

---

docs/rockpi/rockpis/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/download.md

fix: distinguish between official and third-party image

---

docs/zero/zero3/app-development/opencv.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/apps-deployment/opencv.md

Signed-off-by: Nascs Fang <nascs@radxa.com>

feat: port opencv guide to zero3

---

docs/common/dev/_nvme.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/dev/_nvme.mdx

Fix commit

---

docs/x/x4/getting-started/install-os.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/getting-started/install-os.md

为 radxa x4 新增 freebsd 
在 16G+128EMMC 上测试通过。

docs: add freebsd OS

---

docs/compliance/radiofrequency-guidance/pre-env.md
i18n/en/docusaurus-plugin-content-docs/current/compliance/radiofrequency-guidance/pre-env.md

feat: add rtl8852be guidance

---

docs/compute-module/cm3j/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3j/download.md

feat: updated cm3j system download link

---

docs/compute-module/cm3j/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3j/download.md

feat: add hardware docs for cm3j

---

docs/zero/zero3/app-development/sensor.md
docs/zero/zero3/app-development/wiringx.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/app-development/sensor.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/app-development/wiringx.md

Delete zero3 fake info

---

docs/x/x4/bios/update-bios.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/bios/update-bios.md

feat: add x4 bios

---

docs/orion/o6/app-development/artificial-intelligence/npu-introduction.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/app-development/artificial-intelligence/npu-introduction.md

docs: cancel UMD install step in O6 zh/en docs

docs: cancel UMD install step in O6 zh/en docs

---

docs/e/README.md
docs/e/e20c/README.md
docs/e/e52c/README.md

https://github.com/radxa-docs/docs/blob/99b05566582f037109aeb783a63c063d6502de7b/.pre-commit-config.yaml#L16

fix: replace the sidebar_label with title

---

docs/x/x4/bios/update-bios.md
i18n/en/docusaurus-plugin-content-docs/current/x/x4/bios/update-bios.md

fix: fix x4 bios description

---

docs/rock3/rock3a/getting-started/download.md
docs/rock5/rock5c/download.md
docs/rock5/rock5itx/download.md
docs/rock5/rock5t/download.md
docs/rockpi/rockpie/download.md
docs/rockpi/rockpis/download.md
docs/rockpi/rocks0/getting-started/download.md
docs/zero/zero/getting-started/download.md
docs/zero/zero2pro/getting-started/download.md
docs/zero/zero3/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3a/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5itx/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5t/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpie/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpis/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rocks0/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/download.md

Armbian info page

---

docs/rock3/rock3b/download.md
docs/rock3/rock3c/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3b/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock3/rock3c/getting-started/download.md

Openwrt image completion

---

.github/CODEOWNERS
docs/orion/o6/cix-sdk/README.md
docs/orion/o6/cix-sdk/build.md
docs/orion/o6/cix-sdk/get-source.md

增加此芯SDK下载及编译方式说明
初版，先看看还有没有什么要说明的

orion/o6: add initial CIX SDK usage

---

docs/accessories/spi-flash-module.md
docs/rock5/faq.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/spi-flash-module.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/faq.md

fix: update SPI Flash module info

---

docs/compute-module/cm3/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/download.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3j/download.md

feat: add cm3 io hw docs

---

docs/accessories/penta-sata-hat/README.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/README.md

docs: update penta works with

---

docs/rock5/rock5b/low-level-dev/rsdk.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/rsdk.md

fix: rock 5b: low-dev: fix rsdk import name

---

docs/rock5/rock5b/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/download.md

fix: fix the missing batocera link of rock 5b

---

docs/rockpi/rocks0/low-level-dev/rbuild.md
docs/rockpi/rocks0/low-level-dev/rsdk.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rocks0/low-level-dev/rbuild.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rocks0/low-level-dev/rsdk.md

fix: replacerock pi s0 rbuild with rsdk

---

i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/README.md

Fix typos, correct grammar, etc.

---

docs/orion/o6/download.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/download.md

feat: o6: release b6 debian12 image

---

.github/workflows/deploy.yaml

fix: build error

---

docs/orion/o6/download.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/download.md

fix: o6: fix format

---

docs/orion/o6/bios/boot-debian-official-iso.md
docs/orion/o6/bios/install-bios.md
docs/orion/o6/download.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/bios/boot-debian-official-iso.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/bios/install-bios.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/download.md

Signed-off-by: ZHANG Yuntian <yt@radxa.com>

添加O6 RadxaOS及BIOS的相关说明

---

docs/x/README.md
i18n/en/docusaurus-plugin-content-docs/current/x/README.md

fix: x: disable x5

---

docs/rock5/rock5c/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5c/download.md

fix https://github.com/radxa-docs/docs/issues/793

fix: rock-5c: download: add loader image

---

docs/rock5/rock5a/_image.mdx
docs/rock5/rock5a/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/_image.mdx
i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/download.md

fix: rock5: rock-5a: download: fix image list

---

.github/CODEOWNERS
docs/e/e54c/hardware-design/hardware-interface.md
i18n/en/docusaurus-plugin-content-docs/current/e/e54c/hardware-design/hardware-interface.md

fix: modify e54c 14 pin gpio name

---

docs/compute-module/cm5/android/low-level-dev.md
i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/android/low-level-dev.md

fix: fix wrong manifest xml tag for cm5

---

docs/orion/o6/bios/install-bios.md
docs/orion/o6/download.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/bios/install-bios.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/download.md

Update O6 BIOS info

---

.github/CODEOWNERS
docs/e/e24c/README.md
i18n/en/docusaurus-plugin-content-docs/current/e/e24c/README.md

fix: change e24c ram options

---

.github/CODEOWNERS
docs/common/config/_rsetup.mdx
docs/common/radxa-os/_autologin.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/config/_rsetup.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_autologin.mdx

fix: add auto login tip

---

docs/accessories/penta-sata-hat/README.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/README.md

fix: penta add 2x5 pinout

---

docs/cubie/a5e/README.md
docs/zero/zero3/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/cubie/a5e/README.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/getting-started/download.md

- 添加 Zero3 系列的 3D 文件下载链接
- 修改 Zero 3W 产品规格书和 Zero 3W/3E 指向的外壳链接
- 修改 Cubie A5E 全大写的问题 
close #870
close #868

fix: add zero3 3d file and modify a5e readme

---

i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/getting-started/install-system/nvme_system/no_nvme_reader.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/getting-started/install-system/sd_system.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/getting-started/install-system/udisk_system.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/getting-started/quickly_start.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/hardware-use/microsd.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/hardware-use/nvme.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/hardware-use/power_header.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/hardware-use/ufs_emmc_com.md

fix: Correct English translation errors for Q6A

---

docs/zero/zero2pro/getting-started/download.md
i18n/en/docusaurus-plugin-content-docs/current/zero/zero2pro/getting-started/download.md

- 原理图
- 位点图
- 2D 图
- 3D 图
close #872

fix: modify zero2 pro hardware file

---

docs/accessories/peripherals/waveshare-35-display.md
docs/common/accessories/_waveshare-35-display.mdx
docs/common/radxa-os/_remote-access.mdx
docs/common/radxa-os/xfce/_remote-access.mdx
i18n/en/docusaurus-plugin-content-docs/current/accessories/peripherals/waveshare-35-display.md
i18n/en/docusaurus-plugin-content-docs/current/common/accessories/_waveshare-35-display.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_remote-access.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/xfce/_remote-access.mdx

fix: follow the latest Radxa OS to update xorg.conf.d path

---

docs/cubie/a7a/download.md
i18n/en/docusaurus-plugin-content-docs/current/cubie/a7a/download.md

fix: modify a7a android image description

---

docs/aicore/ax-m1/LLM/ds-r1-qwen-1.5b.md
docs/aicore/ax-m1/LLM/ds-r1-qwen-7b.md
docs/aicore/ax-m1/LLM/minicpm4-0.5b.md
docs/aicore/ax-m1/LLM/qwen2.5-1.5b.md
docs/aicore/ax-m1/LLM/qwen3-1.7b.md
docs/aicore/ax-m1/LLM/smolLM2-360m.md

fix: fix the jinja2 package name

fix: fix the jinja2 package name

---

docs/accessories/emmc_module.md
i18n/en/docusaurus-plugin-content-docs/current/accessories/emmc_module.md

fix: add pinout for emmc module

---

docs/dragon/q6a/low-dev/spi_fw.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/low-dev/spi_fw.md

fix: modify Download link

---

docs/cubie/a7a/download.md
i18n/en/docusaurus-plugin-content-docs/current/cubie/a7a/download.md

fix: modify cubie a7a system image link

---

i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/install-system/_use_dd_emmc.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/install-system/_use_dd_nvme.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/install-system/_use_dd_ufs.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/rkdevtool/_emmc.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/rkdevtool/_maskrom.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/rkdevtool/_maskrom_two_device.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/rkdevtool/_spi.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/system-config-debian12/_backsystem.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/system-config-debian12/_eth.mdx

fix: modify common/radxa-os path tutorial motherboard to board

---

.github/CODEOWNERS
docs/orion/o6/download.md
i18n/en/docusaurus-plugin-content-docs/current/orion/o6/download.md

fix: modify orion o6 android download link

---

docs/cubie/a7z/download.md
i18n/en/docusaurus-plugin-content-docs/current/cubie/a7z/download.md

feat: add cubie a7z android download link

---

docs/dragon/q6a/low-dev/build.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/low-dev/build.md

it's a general repo, rename it.

fix: q6a: low-dev: fix the build repo

---

docs/aicore/ax-m1/download.md
i18n/en/docusaurus-plugin-content-docs/current/aicore/ax-m1/download.md

fix: update aicore ax-m1 axcl driver package download link

---

docs/rock2/rock2f/download.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2f/download.md

feat: add rock 2f android system image download link

---

docs/rock2/rock2a/low-level-dev/README.md
docs/rock2/rock2a/low-level-dev/kernel.md
docs/rock2/rock2a/low-level-dev/rsdk.md
docs/rock2/rock2a/low-level-dev/u-boot.md
docs/rock2/rock2f/low-level-dev/README.md
docs/rock2/rock2f/low-level-dev/kernel.md
docs/rock2/rock2f/low-level-dev/rsdk.md
docs/rock2/rock2f/low-level-dev/u-boot.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/low-level-dev/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/low-level-dev/kernel.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/low-level-dev/rsdk.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2a/low-level-dev/u-boot.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2f/low-level-dev/README.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2f/low-level-dev/kernel.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2f/low-level-dev/rsdk.md
i18n/en/docusaurus-plugin-content-docs/current/rock2/rock2f/low-level-dev/u-boot.md

feat: add rock2a/rock2f low level dev tutorial

---

i18n/en/docusaurus-plugin-content-docs/current/common/ai/_aimet.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_fcn-resnet50_qai-app-builder-6490.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_googlenet_qai-app-builder-6490.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_inception_v3_qai-app-builder-6490.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_qai-appbuilder.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_qai-hub-models.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_qairt-install.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_qairt-model-zoo.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_qairt-sdk.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_real-esrgan-x4plus_qai-app-builder-6490.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_yolov8_det_qai-app-builder-6490.mdx
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/app-dev/npu-dev/fcn_resnet50.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/app-dev/npu-dev/inception_v3.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/app-dev/npu-dev/model-zoo.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/app-dev/npu-dev/qai-hub-models.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/app-dev/npu-dev/real_esrgan_x4plus.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/app-dev/npu-dev/yolov8-det.md

feat: add qai-hub-models and update qai-app-builder demos

---

docs/common/ai/_casaos_intro_general.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_casaos_app_install_qualcomm.mdx
i18n/en/docusaurus-plugin-content-docs/current/common/ai/_casaos_intro_general.mdx
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/app-dev/casaos/README.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/app-dev/casaos/casaos_app_install.md
i18n/en/docusaurus-plugin-content-docs/current/dragon/q6a/app-dev/casaos/casaos_intro.md

- translate PR #970 
- 修改 Docker 安装教程的跳转链接

fix: add Dragon Q6A CasaOS en docs

---

docs/aicore/ax-m1/VLM/yolo-world-v2.md

- Sync to Huggingface the latest example process provided by AXERA.

docs: Update the yolo-world-v2.md of ax-m1

---

docs/rockpi/rockpie/download.md
i18n/en/docusaurus-plugin-content-docs/current/rockpi/rockpie/download.md

fix: add rock pi e system image
