radxa-docs/docs

docs/compute-module/cm5/radxa-os/app-dev/wiringx.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/radxa-os/app-dev/wiringx.md
Delete wiringX of Radxa CM5 as it is not currently ported.
=> fix: delete cm5 wiringX

docs/rock5/rock5b/faq.md, docs/rock5/rock5b/getting-started/_maskrom.mdx, docs/rock5/rock5b/low-level-dev/bootloader_spi_flash.md, docs/rock5/rock5b/low-level-dev/erase-spi-from-usb-otg.md, docs/rock5/rock5b/low-level-dev/maskrom.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/faq.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/getting-started/_maskrom.mdx, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5b/low-level-dev/bootloader_spi_flash.md
=> refactor:add faq of rock5b

i18n/en/docusaurus-plugin-content-docs/current/common/general/_serial.mdx
Includes information helpful to users trying to connect to Radxa Zero 3 and other devices at 1.5Mbaud and above.
=> Update _serial.mdx to include high baud instructions for MacOS

docs/accessories/peripherals/waveshare-35-display.md, i18n/en/docusaurus-plugin-content-docs/current/accessories/peripherals/waveshare-35-display.md
#radxa-pkg/radxa-overlays/pull/281
=> perf: add touch configuration of waveshare screen

docs/common/ai/_casaos_app_install.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/ai/_casaos_app_install.mdx
fix the imagesearch and chatdoc docker name in casaos
=> fix: fix the imagesearch and chatdoc docker name in casaos

i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/hardware-design/hardware-interface.md
There are pull-up resistors also I2C3. Also add note about the resistance value.
* Add note about I2C pull-up resistors also being present on I2C4.
* Add note about the resistance being 2.2kOhm
EDIT: Please confirm the validity of these sgtatements before merging. I belive them to be correct. I even tested communicating with a device that doesn't have any i2c pull-ups using both I2C3 and I2C4 and it worked well. The info is taken from the schematic.
=> Add note about I2C pull-ups

docs/common/ai/_casaos_intro.mdx
docs: fix wrong docker path name
=> docs: fix wrong docker path name

docs/x/x4/driver.md, i18n/en/docusaurus-plugin-content-docs/current/x/x4/driver.md
=> fix: fixed pictures and info on x4

docs/nio/nio12l/ubuntu/README.md, docs/nio/nio12l/ubuntu/ubuntu-user-guide.md, i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/ubuntu/README.md, i18n/en/docusaurus-plugin-content-docs/current/nio/nio12l/ubuntu/ubuntu-user-guide.md
=> feat: nio-12l: add ubuntu user guide

docs/common/radxa-os/_mali-gpu.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_mali-gpu.mdx
=> refactor: optimizing string interpretation

docs/rock5/rock5a/getting-started/interface-usage/penta-sata-hat.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/getting-started/interface-usage/penta-sata-hat.md
=> feat: add penta-sata-hat for 5a

docs/zero/zero3/other-os/README.md, docs/zero/zero3/other-os/buildroot.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/other-os/README.md, i18n/en/docusaurus-plugin-content-docs/current/zero/zero3/other-os/buildroot.md
=> feat: add radxa zero 3e buildroot

docs/accessories/penta-sata-hat/README.md, docs/compute-module/cm5/radxa-os/app-dev/ros2_humble.md, i18n/en/docusaurus-plugin-content-docs/current/accessories/penta-sata-hat/README.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/radxa-os/app-dev/ros2_humble.md
=> docs: add penta pinout

.typos.toml, docs/rock5/rock5a/app-development/rk-crypto.md, docs/template/sbc/app-development/rk-crypto.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5a/app-development/rk-crypto.md, i18n/en/docusaurus-plugin-content-docs/current/template/sbc/app-development/rk-crypto.md
Add description about Rockchip Crypto and librkcrypto.
=> feat: add Rockchip Crypto

docs/common/dev/_rtsp.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rtsp.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/general/_power_board_from_40pin.mdx
=> perf: rtsp: replace gst-rtsp-server with mediamtx

docs/common/dev/_gpio.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_gpio.mdx
=> feat: add tip for gpioset

docs/common/radxa-os/_ap.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_ap.mdx
=> feat: radxa-os: add a Q&A for ap

docs/common/dev/_rknn-install.mdx, docs/common/dev/_rknn-toolkit-lite2-yolov5.mdx, docs/common/dev/_rknn-toolkit2.mdx, docs/common/dev/_rknn-ultralytics.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rknn-install.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rknn-toolkit-lite2-yolov5.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rknn-toolkit2.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rknn-ultralytics.mdx
docs: add RK356X NPU enable full steps
close #661
=> docs: add RK356X NPU enable full steps

i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rkdeveloptool.mdx
This patch does not needed anymore.  Patch 73 was merged and patch 85 was already fixed in another commit. So this steps can be removed from wiki.
=> Patches removed for rkdeveloptool

docs/common/dev/_rkdeveloptool.mdx, docs/common/dev/_rkdeveloptoolV2.mdx, docs/common/dev/_rkdeveloptoolV3.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rkdeveloptoolV2.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_rkdeveloptoolV3.mdx
The original repository has merged related branches, no need to manually patch.
- https://github.com/rockchip-linux/rkdeveloptool/pull/73 merged
- https://github.com/rockchip-linux/rkdeveloptool/pull/85 closed, been instead of https://github.com/rockchip-linux/rkdeveloptool/pull/57
=> docs: Outdated command correction

docs/common/radxa-os/_mali-gpu.mdx, i18n/en/docusaurus-plugin-content-docs/current/common/radxa-os/_mali-gpu.mdx
=> fix: mali-gpu: sync documentation updates with Radxa OS

docs/common/dev/_pico2-riscv32-toolchain.mdx, docs/x/x5/README.md, docs/x/x5/software/README.md, docs/x/x5/software/riscv32-tool-chain.md, i18n/en/docusaurus-plugin-content-docs/current/common/dev/_pico2-riscv32-toolchain.mdx, i18n/en/docusaurus-plugin-content-docs/current/x/x5/README.md, i18n/en/docusaurus-plugin-content-docs/current/x/x5/software/README.md, i18n/en/docusaurus-plugin-content-docs/current/x/x5/software/riscv32-tool-chain.md
=> Rp2350 riscv32 tool chain

i18n/en/docusaurus-plugin-content-docs/current/common/dev/_nvme.mdx, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm3/other-os/android/install-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/android/install-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/getting-started/preparation.md, i18n/en/docusaurus-plugin-content-docs/current/compute-module/cm5/radxa-os/install-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/android/install-os.mdx, i18n/en/docusaurus-plugin-content-docs/current/compute-module/nx5/radxa-os/install-os.mdx
=> fix: fix the flash transtation

docs/rock5/rock5t/getting-started/install-os/emmc_boot.md, i18n/en/docusaurus-plugin-content-docs/current/rock5/rock5t/getting-started/install-os/emmc_boot.md
=> feat: add rock5t emmc boot system

docs/e/e20c/download.md, i18n/en/docusaurus-plugin-content-docs/current/e/e20c/download.md
- xfce 系统镜像链接改成cli 系统镜像链接
Closes #863
=> fix: modify e20c debian system link

docs/e/e54c/getting-started/install-os/maskrom/erase.md, docs/e/e54c/getting-started/install-os/spi_flash.md, i18n/en/docusaurus-plugin-content-docs/current/e/e54c/getting-started/install-os/maskrom/erase.md, i18n/en/docusaurus-plugin-content-docs/current/e/e54c/getting-started/install-os/spi_flash.md
- 修改擦除 eMMC 教程
- 增加擦除 / 写入 SPI Flash 教程
=> fix: modify earse emmc and spi flash tutorial

docs/cubie/a7a/download.md, docs/cubie/a7a/getting-started/quickly_start.md, docs/cubie/a7a/hardware-use/emmc-ufs-com.md, i18n/en/docusaurus-plugin-content-docs/current/cubie/a7a/download.md, i18n/en/docusaurus-plugin-content-docs/current/cubie/a7a/getting-started/quickly_start.md, i18n/en/docusaurus-plugin-content-docs/current/cubie/a7a/hardware-use/emmc-ufs-com.md
=> fix: delete cubie a7a cannot boot system tip
